# Generated by Django 5.2.6 on 2025-09-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalyticsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='AnalyticsAp_categor_b8514b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='AnalyticsAp_price_eea72e_idx'),
        ),
    ]
